## Alias
alias clip="xsel -b <"
alias ls="ls --color=auto"
alias cls="clear"
alias run="~/Dotfiles/run"
alias run_re="~/Dotfiles/run_re"
alias utgz="tar -zxvf"
alias tgz="tar -zcvf"
alias unzipGBK="unzip -O gbk"
alias vi="vim"
alias gita="git add -A"
alias gitc="git commit -a -m"
alias gitp="git push"
alias gits="gita; gitc \"Auto commit from Arch Linux.\" && gitp"
