## Alias
alias clip="xsel -b <"
alias ls="ls --color=auto"
alias cls="clear"
alias run="~/Dotfiles/run"
alias run_re="~/Dotfiles/run_re"
alias utgz="tar -zxvf"
alias tgz="tar -zcvf"
alias unzipGBK="unzip -O gbk"
alias vi="vim"
alias gita="git add -A"
alias gitc="git commit -a -S -m"
alias gitp="git push"
alias gits="gita; gitc \"Auto commit from Arch Linux.\" && gitp"
alias sudo="sudo -E"
alias cfw="$HOME/Clash/cfw"
alias virtual="sudo modprobe vboxdrv; sudo modprobe vboxnetadp; sudo modprobe vboxnetflt"
alias s="setsid"
alias q="exit"
alias proxy="export http_proxy=\"http://127.0.0.1:7890\"; export https_proxy=\"http://127.0.0.1:7890\"; export HTTP_PROXY=\"http://127.0.0.1:7890\"; export HTTPS_PROXY=\"http://127.0.0.1:7890\";"
alias unproxy="unset http_proxy; unset https_proxy; unset HTTP_PROXY; unset HTTPS_PROXY;"
